/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CommandeEnvoyeeRouteImport } from './routes/commande-envoyee'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCommandesRouteImport } from './routes/admin/commandes'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminVitrineRouteImport } from './routes/admin/vitrine'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as AdminProduitsIdRouteImport } from './routes/admin/produits.$id'
import { Route as AdminProduitsNouveauRouteImport } from './routes/admin/produits.nouveau'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeEnvoyeeRoute = CommandeEnvoyeeRouteImport.update({
  id: '/commande-envoyee',
  path: '/commande-envoyee',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommandesRoute = AdminCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVitrineRoute = AdminVitrineRouteImport.update({
  id: '/vitrine',
  path: '/vitrine',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProduitsIdRoute = AdminProduitsIdRouteImport.update({
  id: '/produits/$id',
  path: '/produits/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProduitsNouveauRoute = AdminProduitsNouveauRouteImport.update({
  id: '/produits/nouveau',
  path: '/produits/nouveau',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/cgv': typeof CgvRoute
  '/commande-envoyee': typeof CommandeEnvoyeeRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/vitrine': typeof AdminVitrineRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produits/$id': typeof AdminProduitsIdRoute
  '/admin/produits/nouveau': typeof AdminProduitsNouveauRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/cgv': typeof CgvRoute
  '/commande-envoyee': typeof CommandeEnvoyeeRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/vitrine': typeof AdminVitrineRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/produits/$id': typeof AdminProduitsIdRoute
  '/admin/produits/nouveau': typeof AdminProduitsNouveauRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/cgv': typeof CgvRoute
  '/commande-envoyee': typeof CommandeEnvoyeeRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/vitrine': typeof AdminVitrineRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produits/$id': typeof AdminProduitsIdRoute
  '/admin/produits/nouveau': typeof AdminProduitsNouveauRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/a-propos'
    | '/boutique'
    | '/cgv'
    | '/commande-envoyee'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/panier'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tarifs'
    | '/admin/categories'
    | '/admin/commandes'
    | '/admin/messages'
    | '/admin/vitrine'
    | '/produit/$slug'
    | '/admin/'
    | '/admin/produits/$id'
    | '/admin/produits/nouveau'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/cgv'
    | '/commande-envoyee'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/panier'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tarifs'
    | '/admin/categories'
    | '/admin/commandes'
    | '/admin/messages'
    | '/admin/vitrine'
    | '/produit/$slug'
    | '/admin'
    | '/admin/produits/$id'
    | '/admin/produits/nouveau'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/a-propos'
    | '/boutique'
    | '/cgv'
    | '/commande-envoyee'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/panier'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tarifs'
    | '/admin/categories'
    | '/admin/commandes'
    | '/admin/messages'
    | '/admin/vitrine'
    | '/produit/$slug'
    | '/admin/'
    | '/admin/produits/$id'
    | '/admin/produits/nouveau'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CgvRoute: typeof CgvRoute
  CommandeEnvoyeeRoute: typeof CommandeEnvoyeeRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PanierRoute: typeof PanierRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifsRoute: typeof TarifsRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande-envoyee': {
      id: '/commande-envoyee'
      path: '/commande-envoyee'
      fullPath: '/commande-envoyee'
      preLoaderRoute: typeof CommandeEnvoyeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/commandes': {
      id: '/admin/commandes'
      path: '/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AdminCommandesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/vitrine': {
      id: '/admin/vitrine'
      path: '/vitrine'
      fullPath: '/admin/vitrine'
      preLoaderRoute: typeof AdminVitrineRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produits/$id': {
      id: '/admin/produits/$id'
      path: '/produits/$id'
      fullPath: '/admin/produits/$id'
      preLoaderRoute: typeof AdminProduitsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/produits/nouveau': {
      id: '/admin/produits/nouveau'
      path: '/produits/nouveau'
      fullPath: '/admin/produits/nouveau'
      preLoaderRoute: typeof AdminProduitsNouveauRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommandesRoute: typeof AdminCommandesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminVitrineRoute: typeof AdminVitrineRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProduitsIdRoute: typeof AdminProduitsIdRoute
  AdminProduitsNouveauRoute: typeof AdminProduitsNouveauRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommandesRoute: AdminCommandesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminVitrineRoute: AdminVitrineRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProduitsIdRoute: AdminProduitsIdRoute,
  AdminProduitsNouveauRoute: AdminProduitsNouveauRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  BoutiqueRoute: BoutiqueRoute,
  CgvRoute: CgvRoute,
  CommandeEnvoyeeRoute: CommandeEnvoyeeRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PanierRoute: PanierRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifsRoute: TarifsRoute,
  ProduitSlugRoute: ProduitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
